### ISSUE TITLE
flush data periodically before mio%close_connections()

### ISSUE THREAD

**Issue by dsidoren** [ecmwf/multio#10]
Is there a possibility to flush data before close_connections ?
We get a segmentation fault when dump large amount of data which appears at "mio%close_connections()" and the output file is empty. It works with smaller output size. We suspect it tried to write all data at once at the end.

**Comment by dsarmany** [comment]
The interface call ```multio_write_step_complete``` should do that. If you do it periodically, make sure you use different metadata for each checkpoint. In our `multio-hammer` example, we use:
```C++
        // Send flush messages
        Metadata md;
        md.set("name", eckit::Translator<long, std::string>{}(step))
            .set("category", "atms-checkpoint")
            .set("domain", "grid-point");
        for (auto& server : serverPeers) {
            Message flush{Message::Header{Message::Tag::StepComplete, client, *server, Metadata{md}}};
            transport->send(flush);
        }
```
But any metadata that is unique per checkpoint should do. Currently, flush messages aren't selectable so you don't have to change the plan configurations. (We may change this in the future.)

**Comment by raguridan** [comment]
This has been implemented in PR this https://github.com/ecmwf/multio/commit/7651d4f0787b59f17193c254df30c0e9f561bcd1 and the corresponding commit in FESOM2, https://github.com/FESOM/fesom2/commit/1b60fe6af95cf210d6dded4ef224fe1b5795aaac.
