### ISSUE TITLE
Add required order to dependencies PREFIX_PATH variable

### ISSUE THREAD

**Issue by oakleybrunt** [ecmwf/multio#16]
### What maintenance does this project need?

When listing the dependencies in the `ecbuild` call during installation, the dependencies must be listed in a certain order or CMake will not find them all.

The order that works for me is:
1. ecbuild
2. eccodes
3. metkit
4. eckit

**Comment by tlmquintino** [comment]
hi @oakleybrunt thanks for opening this issue.
Can you please give more details on how to reproduce this ?

The issue as described indicates something is wrong in the build. 
The location of dependencies should not have a order when passed to the configuration of ecbuild.
