### ISSUE TITLE
Add server/client example that uses the same FORTRAN executable

### ISSUE THREAD

**Issue by dsidoren** [ecmwf/multio#2]
https://github.com/ecmwf/multio/blob/15d3e10353c893e943183d2a8849dae001e21ff5/src/multio/tools/multio-replay-nemo-fapi.f90#L45

Hi, according to ctest log only 7 (clients, color 777) of 9 processes execute this piece of code. The other 2 (servers, color 888) have been started somewhere else. Assume I have my MPI initialised (9 processes) and have my MPI_COMM_WORLD.  In the "obsolete" multio_nemo.mod we could just use 2 processes to call multio_init_server and the other 7 to call multio_init_client to do the same thing as above. Here I could not detect any server calling thing. Hence I have 2 questions: 

How shall I use "multio_api & fckit_module" effectively to call the server and client from the same executable (or subroutine)?
Where and how do I set colors for client & server?

Thank you!

**Comment by dsarmany** [comment]
Hello,

Yes, the above example currently shows how to interface with multio for the a 'client' application to pass data to post-processing pipelines. In this example, the server starts in a separate executable, `multio-probe`, and the job is launched from a script using MPMD.

This example uses default colours for MPI, set internally within multio. For simple client-server setups, the default should be fine. But for a general use case, the colours can be set via yaml configuration files.  You can find examples in the test configurations: https://github.com/ecmwf/multio/blob/develop/tests/server/config/multio-server-mpi-custom-splitting.yaml.

If you would like to spawn a server using the Fortran interface, you could can add something like this to the Fortran example. Then you would have to make sure that `init` is called on the client side and `init_server` is not the server side. 
```fortran
subroutine init_server(mio_parent_comm)

    integer(8), intent(in) :: mio_parent_comm
    type(multio_configurationcontext) :: cc

    cc%new()

    cerr = cc%mpi_allow_world_default_comm(.FALSE._1)
    cerr = cc%mpi_parent_comm(int(mio_parent_comm))

    cerr = multio_start_server(cc)

    cerr = cc%delete()

end subroutine init_server
```

This will use the same (default) configuration as `multio-probe`. We have not tested this yet, but it should give you the idea. We will add an example that uses a Fortran server in a similar way.

Hope this helps.

**Comment by dsidoren** [comment]
Hello, thank you for the reply. Now I do the following: 1. split the global communicator onto server and client parts. 2. call init_server on the server part. The server does not (always) start failing at multio_start_server(cc). My init_server is as following:

subroutine init_server(mio_parent_comm)
    use fortran_utils
    use multio_api
    use fckit_module
    use fckit_mpi_module
    use multio
    IMPLICIT NONE
    integer, intent(in)               :: mio_parent_comm
    integer                           :: npes, rank, cerr
    type(multio_configurationcontext) :: cc

    cerr = cc%new()
    call MPI_Comm_size(mio_parent_comm, npes, cerr)
    call MPI_Comm_rank(mio_parent_comm, rank, cerr)
    write(0,*) 'init_server starts...PE=', rank
    write(0,*) "Nserver=",                 npes

    cerr = cc%mpi_allow_world_default_comm(.FALSE._1)
    if (cerr /= MULTIO_SUCCESS) ERROR STOP "Error in starting server: mpi_allow_world_default_comm"

    cerr = cc%mpi_parent_comm(mio_parent_comm)
    if (cerr /= MULTIO_SUCCESS) ERROR STOP "Error in starting server: mpi_parent_comm"

    cerr = multio_start_server(cc)
    if (cerr /= MULTIO_SUCCESS) ERROR STOP "Error in starting server: multio_start_server"

    cerr = cc%delete()
    if (cerr /= MULTIO_SUCCESS) ERROR STOP "Error in starting server: delete"

end subroutine init_server

I start the program on 8 cores (2 server and 6 clients). The log of init_server call is:

************************************************
 init_server starts...PE=           1
 Nserver=           2
 multio_new...
 set client id...
 set parent comm...
 set return client comm...
 create new handle...
 init_server starts...PE=           0
 Nserver=           2
Error in starting server: multio_start_server
Error in starting server: multio_start_server
************************************************

At the same time the call of "cerr = mio%new(cc)" fails on the client side for 4 (out of 6) cores (runs successfully only for 2 cores).

Do you have any idea of what is going wrong here? 

The installation of multio went successfully and all tests have been passed:
..................
Start 22: test_multio_replay_nemo_fapi
22/22 Test #22: test_multio_replay_nemo_fapi .....................   Passed    1.39 sec

**Comment by geier1993** [comment]
Actually the plan is to have MULTIO to be configuration driven instead of passing too much things through the API.

However, in terms of MPI we are forced to provide a mechanism that allows passing communicators, because MPI splitting is used done everywhere. 

We may provide mechanisms to use `connect/accept` in the future.

If you don't care about passing communicators at all... it should be possible to pass an empty configuration context and adjust the `mpi-communicators` section:

```
mpi-communicators:
    custom:
        type: split
        color: 1234  # Use a unique color that is not used anywhere else in you application and split from world communicator
        parent: world
    custom-clients:
        type: split
        color: 1
        parent: custom # refer to the section "custom" above
    custom-servers:
        type: split
        color: 2
        parent: custom


....

# In the server section, point to the right MPI group 
server:
  transport: mpi
  group: custom # This will make servers to look up the "custom-servers" group and clients to look for "custom-clients"
  ...

```

You can rename "custom" an arbitrary name. I slightly adjusted the config used by a test: [https://github.com/ecmwf/multio/blob/develop/tests/server/config/multio-server-mpi-custom-splitting.yaml](https://github.com/ecmwf/multio/blob/develop/tests/server/config/multio-server-mpi-custom-splitting.yaml)

There is a "simple" recursive mechanism behind this, which is looking up communicators by names through eckit::mpi.... You may compare with [https://github.com/ecmwf/multio/blob/develop/tests/server/config/multio-server-mpi-default-splitting.yaml](https://github.com/ecmwf/multio/blob/develop/tests/server/config/multio-server-mpi-default-splitting.yaml) to see what's done by default.

**Comment by dsidoren** [comment]
> Hey @dsidoren,
> 
> all instances (server and client) should be started with the same communicator. Multio then splits clients and servers on its own, according to what has been set in the config (or use default values). If you have already split the communicator before passing to the init function, something must go wrong.
> 
> It is important to pass the "parent" communicator and make sure all instances within that communicator are either clients or servers. Using MPI Groups, MULTIO can than compute the ranks of the opposite group.
> 
> For example: Clients split from the parent communicator and can access the group of the parent communicator as well as the group of the client communicator. Using MPI_Group_difference, the group of the server communicator is retrieved and with MPI_Group_translate_ranks the clients can then compute the ranks of server nodes.
> 
> For servers it's vice versa.
> 
> I'm sorry that this is not documented yet. If you think the error is somewhere else, just let me know.

Thank you. I see this is somewhat differs from what was suggested above: https://github.com/ecmwf/multio/issues/2#issuecomment-1335674459

My aim is rather easy for now: I have 8 cores and try to replicate $test_multio_replay_nemo_fapi$ test running on 6 cores and use 2 for the server starting both server and client within a simple fortran program. I had no success until now but will try now what you suggested.

**Comment by geier1993** [comment]
We try to provide this example in the future as well. Currently the `multio-probe` (C++) is really just starting with the default configuration and uses the WORLD communicator without explicitly passing it.

**Comment by raguridan** [comment]
multio integration in FESOM is already available here: https://github.com/FESOM/fesom2/blob/updates_2.5.0.4_de/src/ifs_interface/iom.F90

Closing the issue as obsolete.
